// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBibliotecarioManas.Infra;

namespace SistemaBibliotecarioManas.Infra.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20210924011434_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaBiblitecarioManas.Entities.Entities.LivroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataPublicacao");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Editora");

                    b.Property<int>("GeneroDoLivro")
                        .HasColumnType("int")
                        .HasColumnName("Genero");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Idioma");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NomeAutor");

                    b.Property<string>("NomeLivro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NomeLivro");

                    b.Property<int>("Paginas")
                        .HasColumnType("int")
                        .HasColumnName("Paginas");

                    b.HasKey("Id");

                    b.ToTable("LIVROS");
                });

            modelBuilder.Entity("SistemaBiblitecarioManas.Entities.Entities.PessoaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .HasColumnName("CPF")
                        .IsFixedLength(true);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Nascimento");

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Email");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NomePessoa");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .HasColumnName("Telefone")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.ToTable("PESSOAS");
                });

            modelBuilder.Entity("SistemaBiblitecarioManas.Entities.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Deletado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Email");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NomeUsuario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("SistemaBiblitecarioManas.Entities.Entities.PessoaEntity", b =>
                {
                    b.OwnsOne("SistemaBiblitecarioManas.Entities.Complex_Type.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("PessoaEntityId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Pessoa_Bairro");

                            b1.Property<string>("CEP")
                                .IsRequired()
                                .HasColumnType("varchar(8)")
                                .HasColumnName("Pessoa_CEP");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("varchar(40)")
                                .HasColumnName("Pessoa_Cidade");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasColumnType("varchar(70)")
                                .HasColumnName("Pessoa_Complemento");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar(6)")
                                .HasColumnName("Pessoa_Numero");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("varchar(80)")
                                .HasColumnName("Pessoa_Rua");

                            b1.Property<string>("UF")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Pessoa_UF");

                            b1.HasKey("PessoaEntityId");

                            b1.ToTable("PESSOAS");

                            b1.WithOwner()
                                .HasForeignKey("PessoaEntityId");
                        });

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
